### PR TITLE
 Change from variable  (F*Class) in TKCustomGrid to virtual functions

### PR DESCRIPTION
**Pull request by atlant2011**
1. Small old fix for D7. Incomplete Int64 type support in D7 
2.  Change from variable  (F*Class) in TKCustomGrid to virtual functions returning "*Class". And drop unneed(after apply this patch) functions RealizeCellClass, RealizeColClass,RealizeRowClass

### CODE REVIEW

**Comment by kryslt** [comment]
No way to delete protected or public methods. 
At least keep empty (dummy) methods.
Did you test with all the demos?
Need test at least in your Delphi and latest Lazarus.

**Comment by atlant2011** [comment]
My option speeds up the code a little bit (you don 't have to re-create the objects). And the implementation is also simplified.
>No way to delete protected or public methods.

You can try to leave the empty ones. It is necessary to check.

>Did you test with all the demos?

Currently not fully tested (only latest Lazarus, Delphi - not installed). I 'll test and let you know.

**Comment by atlant2011** [comment]
Sorry, this patch is bad for classic grid with different cell type. I'm test only *dbgrid (with my private prog) with column ones type.
Drop this patch.

**Comment by kryslt** [comment]
Dropped as asked.

**Pull request closed without merging**
